Mynote/myNote/app/models/post.py
# coding:utf-8

from flask import current_app
from app.extensions import db,login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app, request, url_for
from datetime import datetime
import hashlib
import bleach
from markdown import markdown
from app.errors import ValidationError

class Posts(db.Model):

    __tablename__ = 'posts'
    id = db.Column(db.Integer,primary_key=True)
    # 回复id
    rid = db.Column(db.Integer, index=True,default=0)
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime,default=datetime.utcnow)
    # 指定外键
    uid = db.Column(db.Integer,db.ForeignKey('users.id'))

    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    summury = db.Column(db.Text)
    summury_html = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))

    def to_json(self):
        json_post = {
            'url': url_for('api.get_post', id=self.id, _external=True),
            'body': self.body,
            'body_html': self.body_html,
            'timestamp': self.timestamp,
            'author': url_for('api.get_user', id=self.uid,
                              _external=True),
        }
        return json_post

    @staticmethod
    def from_json(json_post):
        body = json_post.get('body')
        if body is None or body == '':
            raise ValidationError('post does not have a body')
        return Posts(body=body)

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p', 'img']
        attrs = {
            '*': ['class'],
            'a': ['href', 'rel'],
            'img': ['src', 'alt']
        }
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, attributes=attrs, strip=True))

    @staticmethod
    def on_changed_summury(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'code', 'blockquote', 'em', 'i',
                        'strong', 'li', 'ol', 'pre', 'strong', 'ul', 'h1', 'h2', 'h3', 'p']
        target.summury_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, strip=True))



db.event.listen(Posts.body, 'set', Posts.on_changed_body)
db.event.listen(Posts.summury, 'set', Posts.on_changed_summury)



class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(64),unique=True)
    posts = db.relationship('Posts',backref='category',lazy='dynamic')

    @staticmethod
    def insert_categories():
        categories = [u'web开发', u'数据挖掘', u'flask', u'python', u'爬虫', u'前端开发', u'基础知识', u'笔记', u'随记']
        for category in categories:
            postcategory=Category.query.filter_by(name=category).first()
            if postcategory is None:
                postcategory = Category(name=category)
                db.session.add(postcategory)
        db.session.commit()

    def __repr__(self):
        return '<Category %r>' % self.name

Mynote/myNote/app/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,StringField,SelectField
from flask_pagedown.fields import PageDownField

from wtforms.validators import DataRequired,Length
from ..models.post import Category

class PostsForm(FlaskForm):
    # 想要设置字段的其他属性，可以通过render_kw完成

    # content = TextAreaField('',render_kw={'placeholder':'分享此刻心情...'}
    #                         ,validators=[DataRequired(),Length(1,128,message='字数超出限制')])
    # submit = SubmitField('发送')

    title = StringField(u'标题', validators=[DataRequired()])
    body = PageDownField(u'内容', validators=[DataRequired()])
    summury = PageDownField(u'摘要', validators=[DataRequired()])
    category = SelectField(u'分类',coerce=int)
    submit = SubmitField(u'提交')

    def __init__(self, *args, **kwargs):
        super(PostsForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name) for category
            in Category.query.order_by(Category.name).all()]

Mynote/myNote/app/views/main.py
# coding:utf-8
from flask import Blueprint, render_template,current_app,request
from ..models import Posts,Category
from werkzeug.security import generate_password_hash,check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


main = Blueprint('main',__name__)

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('main/index.html')

@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('main/about.html')

@main.route('/waiting', methods=['GET', 'POST'])
def waiting():
    return render_template('main/waiting.html')

@main.route('/archives', methods=['GET', 'POST'])
def archives():
    # 时间，类别，全局搜索查询
    posts = Posts.query
    category = Category.query
    posts_num = Posts.query.count()
    num = Category.query.count()

    return render_template('main/archives.html', category=category,category_num=num,posts_num=posts_num)


@main.route('/good', methods=['GET', 'POST'])
def good():
    from app.models import Posts

    page = request.args.get('page',1,type=int)
    pagination = ((Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()))).paginate(page,per_page=2,error_out=False)
    posts = pagination.items

    return render_template('main/good.html',posts=posts,pagination=pagination)


@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):

    post = Posts.query.get_or_404(id)
    # form = CommentForm()
    # if form.validate_on_submit():
    #     comment = Comment(body=form.body.data,
    #                         post=post,
    #                         author=current_user._get_current_object())
    #     db.session.add(comment)
    #     flash(u'留言成功')
    #     return redirect(url_for('.post', id=post.id, page=-1))
    # page = request.args.get('page', 1, type=int)
    # if page == -1:
    #     page = (post.comments.count() -1) / \
    #             current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    # pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
    #     page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
    #     error_out=False)

    return render_template('main/post.html', post=post)

@main.route('/category/<int:id>')
def category(id):

    category = Category.query.get_or_404(id)
    # posts = category.posts.order_by(Posts.timestamp.desc())
    page = request.args.get('page',1,type=int)
    pagination = category.posts.order_by(Posts.timestamp.desc()).paginate(
        page,per_page=current_app.config['FLASK_POSTS_PER_PAGE'],
        error_out=False
    )
    posts = pagination.items
    return render_template('main/category.html',category=category,posts=posts,pagination=pagination)
#
# # ------------------------------------ #
# @main.route('/secret')
# def secret():
#     return generate_password_hash('psw')
#
# @main.route('/check/<psw>')
# def check(psw):
#     # 密码校验函数：输入加密后的的值，密码
#     if check_password_hash(
#         'pbkdf2:sha256:150000$VIDe0YJP$af0438e54cc1f33f8310787c44eec57f500eafa27c0d7fbbfc56b149aff0ce1f',
#         psw
#     ):
#         return '密码正确'
#     else:
#         return '密码错误'
# # ============================ #
#
# # ---------------------------- #
# @main.route('/generate_token/')
# def generate_token():
#     s = Serializer(current_app.config['SECRET_KEY'],expires_in=3600)
#     # 加密指定数据，以字典的形式传入
#     return s.dumps({'id':10})
#
# @main.route('/activate/<token>')
# def activate(token):
#     s = Serializer(current_app.config['SECRET_KEY'])
#     try:
#         data = s.loads(token)
#     except:
#         return 'token错误'
#     return str(data.get('id'))
# # ============================ #

Mynote/myNote/app/views/user.py
# coding:utf-8
from flask import Blueprint,render_template,flash,redirect,url_for,current_app,request,abort
from app.forms import RegisterForm,LoginForm,PasswordForm,IconForm,PostsForm
from app.email import send_email
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.models import User,Posts,Category
from app.extensions import db,LoginManager,photos
from flask_login import login_user,logout_user,login_required,current_user
import random
import os
from PIL import Image


user = Blueprint('user',__name__)


@user.before_app_request
def before_request():
    if current_user.is_authenticated:
        # current_user.ping()
        if not current_user.confirmed \
                and request.endpoint \
                and request.endpoint[:5] != 'user.' \
                and request.endpoint != 'static':
            return redirect(url_for('user.unconfirmed'))


@user.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('main.index'))
    return render_template('user/unconfirmed.html')


@user.route('/confirm')
@login_required
def resend_confirmation():  # 重新发送确认邮件

    token = current_user.generate_activate_token()
    send_email(current_user.email, '账户激活', 'email/account_activate', token=token, username=current_user.username)
    flash('a confirm email has been sent to your email.')
    return redirect(url_for('user.login'))



@user.route('/login/',methods=['GET','POST'])
def login():

    form = LoginForm()
    if current_user.is_authenticated:
        if current_user.confirmed:
            flash('您已登陆.')
            return redirect(url_for('main.index'))
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if u is None:
            flash('无效用户名')
        elif u.verify_password(form.password.data):
            if not u.confirmed:
                return render_template('user/unconfirmed.html')
            else:
                # 验证通过，用户登录,并完成记住我功能
                login_user(u,remember=form.remember_me.data)
                # 如果有下一跳跳转地址就跳转到下一地址，没有进入管理页面
                return redirect(request.args.get('next') or url_for('user.profile'))
        else:
            flash('无效密码')
            # return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)

@user.route('/register/',methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 有效提交

        # 创建对象，写入数据库
        u = User(username=form.username.data,password=form.password.data,email=form.email.data)
        # 发送激活邮件
        # s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
        db.session.add(u)
        db.session.commit()
        # 生成校验条件
        token = u.generate_activate_token()

        flash('激活邮件已发送，请查收')
        send_email(form.email.data,'账户激活','email/account_activate',token=token,username=form.username.data)
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)


@user.route('/activate/<token>')
def activate(token):
    # s = Serializer(current_app.config['SECRET_KEY'])
    # try:
    #     data = s.loads(token)
    # except:
    #     return 'token错误'
    # return '%d号账户已激活' % data.get('id')
    if User.check_activate_token(token):
        flash('账户激活成功')
        return redirect(url_for('user.login'))
    else:
        flash('账户激活失败')
        return redirect(url_for('main.index'))


@user.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('已经退出登录')
    return redirect(url_for('main.index'))


@user.route('/manage/')
@login_required
def profile():
    return render_template('user/profile.html')


@user.route('/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_psw.data):
            current_user.password=form.new_psw.data
            db.session.add(current_user)
            flash('密码已修改完')
            return redirect(url_for('main.index'))
        else:
            flash('密码错误')
            return redirect(url_for('user.change_password'))
    return render_template('user/change_password.html',form=form)

@user.route('/change_icon/',methods=['GET','POST'])
@login_required
def change_icon():
    form = IconForm()
    if form.validate_on_submit():
        # 生成随机文件名
        suffix = os.path.splitext(form.icon.data.filename)[1]
        name = rand_str() + suffix
        photos.save(form.icon.data,name=name)
        # 生成缩略图
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],name)
        img = Image.open(pathname)
        img.thumbnail((64,64))
        img.save(pathname)
        # 更换头像
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))
        # 保存新头像
        current_user.icon = name
        db.session.add(current_user)
        flash('头像已上传更新')
    return render_template('user/change_icon.html',form=form)


# 生成随机字符串
def rand_str(length=32):
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(random.choice(base_str) for _ in range(length))



@user.route('/getnote/',methods=['GET','POST'])
@login_required
def  note():
    form = PostsForm()
    post = Posts()
    if form.validate_on_submit():
        u = current_user._get_current_object()
        post.title = form.title.data
        post.body = form.body.data
        post.summury = form.summury.data
        post.category = Category.query.get(form.category.data)
        post.uid = u.id
        db.session.add(post)
        flash('已发送')
        return redirect(url_for('main.good'))
    return render_template('user/getnote.html',form=form)

@user.route('/editnote/<int:id>', methods=['GET', 'POST'])
@login_required
def editnote(id):
    post = Posts.query.get_or_404(id)
    # if current_user != post.author and \
    #         not current_user.can(Permission.ADMINISTER):
    #     abort(403)
    form = PostsForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.body=form.body.data
        post.summury=form.summury.data
        post.category=Category.query.get(form.category.data)
        db.session.add(post)
        flash(u'文章已更新')
        return redirect(url_for('main.post', id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.summury.data = post.summury
    form.category.data = post.category_id
    return render_template('user/editnote.html', form=form)

@user.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):

    post = Posts.query.get_or_404(id)
    title = post.title
    db.session.delete(post)
    flash(f'文章[ { title } ]已删除')
    return redirect(url_for('main.good'))


@user.route('/batchop/', methods=['GET', 'POST'])
@login_required
def manage_del_mod():
    from app.models import Posts
    page = request.args.get('page', 1, type=int)
    pagination = ((Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()))).paginate(page, per_page=2,                                                                             error_out=False)
    posts = pagination.items
    # return render_template('main/good.html', posts=posts, pagination=pagination)

    post_ids = request.values.getlist('array')
    print(post_ids)
    #提交删除后为跳转刷新
    if post_ids:
        for post_id in post_ids:
            post = Posts.query.get_or_404(int(post_id))
            title = post.title
            db.session.delete(post)
            # todo 改为弹窗
            flash(f'文章[ { title } ]已批量删除')
        return redirect(url_for('user.manage_del_mod'))
    return render_template('user/batchop.html',posts=posts, pagination=pagination)

Mynote/myNote/app/templates/main/about.html
{% extends 'base/base.html' %}

{% block title %} about {% endblock %}

{% block page_content %}
<body>
<div class="container"><!--1170px-->
    <div class="jumbotron">
        <h2>关于网站</h2>
        <p>开源</p>
        <button class="btn btn-default">快速进入</button>
    </div>
</div>



{#<script src="vend/jquery/jquery.js"></script>#}
{#<script src="vendor/bootstrap/js/bootstrap.js"></script>#}
{#<script src="js/main.js"></script>#}
</body>

{% endblock %}

Mynote/myNote/app/templates/main/all_post.html
{% for post in posts %}
    <article class="article the-font" style="box-shadow: rgb(167, 163, 163) 10px 10px 20px;background:#fffffc;">
        <a href="/post/{{ post.id }}"><h3 style="color:#34495E">{{ post.title }}</h3></a>
        <p style="padding-left:20px;">
            <small>
            <span class="glyphicon glyphicon-calendar" aria-hidden="true">|</span>
            <span style="color:#8C8C8C;"> {{ moment(post.timestamp).format('YYYY/MM/DD hh:mm:ss') }}</span>
            </small>
            <a href="{{ url_for('main.category',id=post.category.id) }}">
                <span class="label label-success"><i class="fa fa-paperclip"
                                                     aria-hidden="true"></i> {{ post.category.name }}</span>
            </a>


        </p>

        <h6 style="padding-left:20px;">&nbsp;版权声明：本文版权归作者所有，转载请注明地址。</h6>

        <div class="post-body">
            {% if post.summury_html %}
                {{ post.summury_html | safe }}
            {% else %}
                {{ post.summury }}
            {% endif %}
        </div>

        <div style="border-top:1px solid #EBEBEB;padding:20px 5px;margin-bottom:20px;">
            <span style="float:right;">
{#                <a href="{{ url_for('.post', id=post.id) }}#comments">#}
{#                    <button class="btn  btn-info">#}
{#                        <i class="fa fa-commenting" aria-hidden="true"></i> {{ post.comments.count() }} 评论#}
{#                    </button>#}
{#                </a>#}
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('user.editnote', id=post.id) }}">
                    <button class="btn  btn-primary"><i class="fa fa-pencil-square-o"
                                                        aria-hidden="true"></i> 编辑</button>
                </a>
                {% endif %}
                <a href="{{ url_for('.post', id=post.id) }}">
                    <button class="btn  btn-inverse"><i class="fa fa-chevron-circle-down"
                                                        aria-hidden="true"></i> 详情</button>
                </a>

            </span>
        </div>

    </article>
    <br>
{% endfor %}

Mynote/myNote/app/templates/main/archives.html
{% extends 'base/base.html' %}

{% block title %} about {% endblock %}

{% block page_content %}
<body>
<div class="container"><!--1170px-->
    <div class="jumbotron">
        <h2>所有文章({{ posts_num }})</h2>
        <p>快速进入</p>
        <button class="btn btn-default">切换类别</button>

         <p style="padding-left:20px;">
            <small>
                <span class="fa fa-paperclip glyphicon glyphicon-calendar " aria-hidden="true"></span>
{#            <span style="color:#8C8C8C;"> {{ moment(post.timestamp).format('YYYY/MM/DD hh:mm:ss') }}</span>#}
            </small>
             {% for category in category %}
            <a href="{{ url_for('main.category',id=category.id) }}">
                <span class="label"><i class="fa" aria-hidden="true"></i> {{ category.name }}({{ category.posts.count() }})</span>
            </a>
                {% endfor %}
         </p>
          <button class="btn btn-default">切换年份</button>

         <p style="padding-left:20px;">
            <small>
            <span class="glyphicon glyphicon-calendar" aria-hidden="true">|</span>
{#            <span style="color:#8C8C8C;"> {{ moment(post.timestamp).format('YYYY/MM/DD hh:mm:ss') }}</span>#}
            </small>


        </p>
    </div>
</div>



{#<script src="vend/jquery/jquery.js"></script>#}
{#<script src="vendor/bootstrap/js/bootstrap.js"></script>#}
{#<script src="js/main.js"></script>#}
</body>

{% endblock %}

Mynote/myNote/app/templates/main/category.html
{% extends "base/base.html" %}
{% from 'base/macro.html' import pagination_show %}

{% block title %}{{ category.name }}{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4><i class="fa fa-paperclip" aria-hidden="true"></i> {{ category.name }}({{ category.posts.count() }})</h4><br/>
                {% include 'main/all_post.html' %}

            <div class="justify-content-center ">
              {{ pagination_show(pagination,'main.category',id=category.id) }}
            </div>


        </div>

        {#        {% if pagination %}#}
{#        <div style="float:right">{{ macros.pagination_widget(pagination, '.category',id=category.id) }}</div>#}
{#        {% endif %}#}
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

Mynote/myNote/app/templates/main/good.html
{% extends 'base/base.html' %}

{% from 'base/macro.html' import pagination_show %}

{% block title %} justNote {% endblock %}

{% block page_content %}

    <hr class="m-0">

    <section class="resume-section p-3 p-lg-5 d-flex justify-content-center" id="experience">
      <div class="w-100">
        <h3 class="mb-5">最新文章</h3>

          <hr class="m-6">

          {# ffdfdfdffff #}
      {% include 'main/all_post.html' %}
          <div class="justify-content-center ">
          {{ pagination_show(pagination,'main.good') }}
          </div>
{#      {% for post in posts %}#}
{#    <article class="article the-font" style="box-shadow: rgb(167, 163, 163) 5px 5px 20px;background:#fffffc;">#}
{#        <a href="/post/{{ post.id }}"><h3 style="color:#34495E">{{ post.title }}</h3></a>#}
{#        <p style="padding-left:20px;">#}
{##}
{#                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>#}
{#                <span style="color:#8C8C8C;"> {{ moment(post.timestamp).format('YYYY/MM/DD hh:mm:ss') }}</span>#}
{#            </small>#}
{#            <a href="{{ url_for('main.category',id=post.category.id)}}">#}
{#                <span class="label label-success"><i class="fa fa-paperclip" aria-hidden="true"></i> {{ post.category.name }}</span>#}
{#            </a>#}
{#        </p>#}
{#        <div class="post-alert">版权声明：本文版权归作者所有，转载请注明地址。</div>#}
{##}
{#        <div class="post-body">#}
{#        {% if post.summury_html %}#}
{#        {{ post.summury_html | safe }}#}
{#        {% else %}#}
{#        {{ post.summury }}#}
{#        {% endif %}#}
{#        </div>#}
{##}
{#        <div style="border-top:1px solid #EBEBEB;padding:20px 5px;margin-bottom:20px;">#}
{#            <span style="float:right;">#}
{#                <a href="{{ url_for('.post', id=post.id) }}#comments">#}
{#                    <button class="btn  btn-info">#}
{#                        <i class="fa fa-commenting" aria-hidden="true"></i> {{ post.comments.count() }} 评论#}
{#                    </button>#}
{#                </a>#}
{#                {% if current_user.is_authenticated %}#}
{#                <a href="{{ url_for('user.editnote', id=post.id) }}">#}
{#                    <button class="btn  btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</button>#}
{#                </a>#}
{#                {% endif %}#}
{#                <a href="{{ url_for('.post', id=post.id) }}">#}
{#                    <button class="btn  btn-inverse"><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> 详情</button>#}
{#                </a>#}
{##}
{#            </span>#}
{#        </div>#}
{##}
{#    </article>#}


      {#    hhhhhh#}
{#    <div class="row">#}
{#        <div class="col-md-8">#}
{##}
{#            {% for p in posts %}#}
{##}
{#                <div class="media">#}
{#                    <div class="media-left">#}
{#                        <a href="#">#}
{#                            <img class="media-object" src="{{ url_for('static',filename='upload/'+p.user.icon) }}"#}
{#                                 style="height: 64px;width: 64px" alt="icon">#}
{#                        </a>#}
{#                    </div>#}
{#                    <div class="media-body">#}
{#                        <div class="media-heading">#}
{#                            <h4><a href="/post/{{ p.id }}"><h3 style="color:#34495E">{{ p.title }}</h3></a></h4>#}
{#                            <h6>{{ p.timestamp }}</h6>#}
{#                        </div>#}
{#                        <div class="post-body">#}
{#        {% if p.summury_html %}#}
{#        {{ p.summury_html | safe }}#}
{#        {% else %}#}
{#        {{ post.summury }}#}
{#        {% endif %}#}
{#        </div>#}
{##}
{#                    </div>#}
{#                </div>#}
{#                <hr/>#}
{#            {% endfor %}#}
{##}
{#        </div>#}
{#        <div class="col-md-4">#}
{##}
{#        </div>#}
{#    </div>#}



      </div>

    </section>


{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

Mynote/myNote/app/templates/main/post.html
{% extends "base/base.html" %}
{#{% import "_macros.html" as macros %}#}
{#{% import "bootstrap/wtf.html" as wtf %}#}

{% block title %}文章{% endblock %}

{% block page_content %}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <article class="article the-font" style="box-shadow: rgb(167, 163, 163) 5px 5px 20px;background:#fffffc;">
                <h2>{{ post.title }}</h2>
                <p style="padding-left:20px;">
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                    <a href="{{ url_for('user.profile', username=post.user.username) }}"> {{ post.user.username }}</a> &nbsp
                    <small>
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true">|</span>
                        <span style="color:#8C8C8C;"> {{ moment(post.timestamp).format('YYYY/MM/DD hh:mm:ss')  }}</span>
                    </small>
                    <a href="{{ url_for('main.category',id=post.category.id)}}"><span class="label label-success"><i class="fa fa-paperclip" aria-hidden="true"></i> {{ post.category.name }}</span></a>
                </p>
                
                <div class="post-author">
                    
                </div>
                <h6 style="padding-left:20px;">&nbsp;版权声明：本文版权归作者所有，转载请注明地址。</h6>
                
                <div class="post-body">
                {% if post.body_html %}
                {{ post.body_html | safe }}
                {% else %}
                {{ post.body }}
                {% endif %}
                </div>
                <div style="border-top:1px solid #EBEBEB;padding:10px 5px;margin-top:20px;">
                    <span style="float:right">
{#                        <a href="{{ url_for('.post', id=post.id) }}#comments"><span class="label label-primary"><i class="fa fa-commenting" aria-hidden="true"></i> {{ post.comments.count() }} 评论</span></a>#}
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('user.editnote', id=post.id) }}"><span class="label label-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</span></a>
{#                            <a href="{{ url_for('user.delete', id=post.id) }}"><span class="label label-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 删除</span></a>#}
<a href="{{ url_for('user.delete', id=post.id) }}"
    onclick="{if(confirm('确定纪录吗?')){this.document.formname.submit();return true;}return false;}"><span class="label label-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>删除</span></a>

{#                        {% elif current_user.is_administrator() %}#}
{#                        <a href="{{ url_for('.edit', id=post.id) }}"><span class="label label-danger">编辑 [管理员]</span></a>#}
                        {% endif %}
                        <a href="/" class="btn btn-xs ">返回首页<span class=" glyphicon glyphicon-log-out" aria-hidden="true"></span></a>
                    </span>
                </div>
            </article>
        </div>
    </div>
</div>

{#<div class="container">#}
{#    <div class="row" style="padding:50px 20px;">#}
{#        <h4 id="comments"><i class="fa fa-commenting" aria-hidden="true"></i> 评论：</h4>#}
{#        {% if current_user.can(Permission.COMMENT) %}#}
{#        <div class="comment-form">#}
{#            {{ wtf.quick_form(form) }}#}
{#        </div>#}
{#        {% endif %}#}
{#        {% include '_comments.html' %}#}
{#    </div>#}
{#</div>#}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
    {{ moment.include_moment() }}

{% endblock %}

Mynote/myNote/app/templates/main/waiting.html
{% extends 'base/base.html' %}

{% block title %} about {% endblock %}

{% block page_content %}
<body>
<div class="container"><!--1170px-->
    <div class="jumbotron">
        <h2>网站标题</h2>
        <p>我是内网入口！！！！</p>
        <button class="btn btn-default">快速进入</button>
    </div>
</div>



{#<script src="vend/jquery/jquery.js"></script>#}
{#<script src="vendor/bootstrap/js/bootstrap.js"></script>#}
{#<script src="js/main.js"></script>#}
</body>

{% endblock %}