Mynote/myNote/app/models/user.py
# coding:utf-8
from flask import current_app
from app.extensions import db,login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


class User(UserMixin,db.Model):
    # 指定表名
    __tablename__ = 'users'

    # def __init__(self):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(32),unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(64),unique=True)
    confirmed = db.Column(db.Boolean,default=False)
    # 添加头像字段，并迁移数据
    icon = db.Column(db.String(64),unique=False,default='default.jpg')

    # member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    # last_seen = db.Column(db.DateTime(), default=datetime.utcnow)

    # 添加关联
    # 参数说明
    # 第一个参数，唯一一个必须参数，关联模型类名
    # backref:反向引用的字段名
    # lazy:指定加载关联数据的方式，dynamic不加载数据，但是提供关联查询
    posts = db.relationship('Posts',backref='user',lazy='dynamic')


    # 对指定字段进行处理，保护字段
    @property
    def password(self):
        raise ArithmeticError('密码不可读')
    # 设置密码，加密存储
    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    # 密码校验
    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    # 生成用户激活的token
    def generate_activate_token(self,expires_in=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expires_in)
        token = s.dumps({'id': self.id})
        return token

    # 激活账户时的token校验，校验时还不知道用户信息，需要静态方法
    @staticmethod
    def check_activate_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        user = User.query.get(data.get('id'))
        if user is None:
            # 用户不存在
            return False
        if not user.confirmed:
            user.confirmed = True
            db.session.add(user)
        return True

    # def ping(self):
        #     self.last_seen = datetime.utcnow()
        #     db.session.add(self)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

Mynote/myNote/app/forms/user.py
# coding:utf-8

from flask_wtf import FlaskForm
from flask_wtf.file import FileField,FileRequired,FileAllowed
# 导入字段
from wtforms import StringField,PasswordField,SubmitField,ValidationError,BooleanField
# 导入验证器类
from wtforms.validators import DataRequired,Email,EqualTo,Length
from app.models import User
from app.extensions import photos


# 注册表单类
class RegisterForm(FlaskForm):
    username  = StringField('用户名',validators=[DataRequired(),Length(6,19,message='用户名长度在6~18个字符之间')])
    password  = StringField('密码',validators=[DataRequired(),Length(6,19,message='密码长度在6~18个字符之间')])
    confirm = PasswordField('确认密码',validators=[EqualTo('password',message='两次密码不一致')])
    email = StringField('邮箱',validators=[Email(message='邮箱格式不正确')])
    submit = SubmitField('立即注册')


    # 自定义验证器，验证用户名
    def validate_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户名已存在，请再想其他用户名')

    # 自定义验证器，验证邮箱
    def validate_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已存在，请使用其他邮箱')


# 登陆表单类
class LoginForm(FlaskForm):

    username = StringField('用户名', validators=[DataRequired()])
    password = PasswordField('密码', validators=[DataRequired()])
    remember_me = BooleanField('记住我')
    submit = SubmitField('立即登录')

# 修改密码表单类
class PasswordForm(FlaskForm):

    old_psw = StringField('原密码', validators=[DataRequired()])
    new_psw = StringField('新密码',validators=[DataRequired(),Length(6,19,message='密码长度在6~18个字符之间')])
    confirm = PasswordField('确认密码', validators=[EqualTo('new_psw', message='两次密码不一致')])
    submit = SubmitField('确认修改')


# 修改头像表单
class IconForm(FlaskForm):

    icon = FileField('头像',validators=[FileRequired('请选择上传的文件'),FileAllowed(photos,'只能上传图片')]  )
    submit = SubmitField('点击上传')

Mynote/myNote/app/views/user.py
# coding:utf-8
from flask import Blueprint,render_template,flash,redirect,url_for,current_app,request,abort
from app.forms import RegisterForm,LoginForm,PasswordForm,IconForm,PostsForm
from app.email import send_email
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.models import User,Posts,Category
from app.extensions import db,LoginManager,photos
from flask_login import login_user,logout_user,login_required,current_user
import random
import os
from PIL import Image


user = Blueprint('user',__name__)


@user.before_app_request
def before_request():
    if current_user.is_authenticated:
        # current_user.ping()
        if not current_user.confirmed \
                and request.endpoint \
                and request.endpoint[:5] != 'user.' \
                and request.endpoint != 'static':
            return redirect(url_for('user.unconfirmed'))


@user.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('main.index'))
    return render_template('user/unconfirmed.html')


@user.route('/confirm')
@login_required
def resend_confirmation():  # 重新发送确认邮件

    token = current_user.generate_activate_token()
    send_email(current_user.email, '账户激活', 'email/account_activate', token=token, username=current_user.username)
    flash('a confirm email has been sent to your email.')
    return redirect(url_for('user.login'))



@user.route('/login/',methods=['GET','POST'])
def login():

    form = LoginForm()
    if current_user.is_authenticated:
        if current_user.confirmed:
            flash('您已登陆.')
            return redirect(url_for('main.index'))
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if u is None:
            flash('无效用户名')
        elif u.verify_password(form.password.data):
            if not u.confirmed:
                return render_template('user/unconfirmed.html')
            else:
                # 验证通过，用户登录,并完成记住我功能
                login_user(u,remember=form.remember_me.data)
                # 如果有下一跳跳转地址就跳转到下一地址，没有进入管理页面
                return redirect(request.args.get('next') or url_for('user.profile'))
        else:
            flash('无效密码')
            # return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)

@user.route('/register/',methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 有效提交

        # 创建对象，写入数据库
        u = User(username=form.username.data,password=form.password.data,email=form.email.data)
        # 发送激活邮件
        # s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
        db.session.add(u)
        db.session.commit()
        # 生成校验条件
        token = u.generate_activate_token()

        flash('激活邮件已发送，请查收')
        send_email(form.email.data,'账户激活','email/account_activate',token=token,username=form.username.data)
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)


@user.route('/activate/<token>')
def activate(token):
    # s = Serializer(current_app.config['SECRET_KEY'])
    # try:
    #     data = s.loads(token)
    # except:
    #     return 'token错误'
    # return '%d号账户已激活' % data.get('id')
    if User.check_activate_token(token):
        flash('账户激活成功')
        return redirect(url_for('user.login'))
    else:
        flash('账户激活失败')
        return redirect(url_for('main.index'))


@user.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('已经退出登录')
    return redirect(url_for('main.index'))


@user.route('/manage/')
@login_required
def profile():
    return render_template('user/profile.html')


@user.route('/change_password/',methods=['GET','POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_psw.data):
            current_user.password=form.new_psw.data
            db.session.add(current_user)
            flash('密码已修改完')
            return redirect(url_for('main.index'))
        else:
            flash('密码错误')
            return redirect(url_for('user.change_password'))
    return render_template('user/change_password.html',form=form)

@user.route('/change_icon/',methods=['GET','POST'])
@login_required
def change_icon():
    form = IconForm()
    if form.validate_on_submit():
        # 生成随机文件名
        suffix = os.path.splitext(form.icon.data.filename)[1]
        name = rand_str() + suffix
        photos.save(form.icon.data,name=name)
        # 生成缩略图
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],name)
        img = Image.open(pathname)
        img.thumbnail((64,64))
        img.save(pathname)
        # 更换头像
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))
        # 保存新头像
        current_user.icon = name
        db.session.add(current_user)
        flash('头像已上传更新')
    return render_template('user/change_icon.html',form=form)


# 生成随机字符串
def rand_str(length=32):
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(random.choice(base_str) for _ in range(length))



@user.route('/getnote/',methods=['GET','POST'])
@login_required
def  note():
    form = PostsForm()
    post = Posts()
    if form.validate_on_submit():
        u = current_user._get_current_object()
        post.title = form.title.data
        post.body = form.body.data
        post.summury = form.summury.data
        post.category = Category.query.get(form.category.data)
        post.uid = u.id
        db.session.add(post)
        flash('已发送')
        return redirect(url_for('main.good'))
    return render_template('user/getnote.html',form=form)

@user.route('/editnote/<int:id>', methods=['GET', 'POST'])
@login_required
def editnote(id):
    post = Posts.query.get_or_404(id)
    # if current_user != post.author and \
    #         not current_user.can(Permission.ADMINISTER):
    #     abort(403)
    form = PostsForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.body=form.body.data
        post.summury=form.summury.data
        post.category=Category.query.get(form.category.data)
        db.session.add(post)
        flash(u'文章已更新')
        return redirect(url_for('main.post', id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.summury.data = post.summury
    form.category.data = post.category_id
    return render_template('user/editnote.html', form=form)

@user.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):

    post = Posts.query.get_or_404(id)
    title = post.title
    db.session.delete(post)
    flash(f'文章[ { title } ]已删除')
    return redirect(url_for('main.good'))


@user.route('/batchop/', methods=['GET', 'POST'])
@login_required
def manage_del_mod():
    from app.models import Posts
    page = request.args.get('page', 1, type=int)
    pagination = ((Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()))).paginate(page, per_page=2,                                                                             error_out=False)
    posts = pagination.items
    # return render_template('main/good.html', posts=posts, pagination=pagination)

    post_ids = request.values.getlist('array')
    print(post_ids)
    #提交删除后为跳转刷新
    if post_ids:
        for post_id in post_ids:
            post = Posts.query.get_or_404(int(post_id))
            title = post.title
            db.session.delete(post)
            # todo 改为弹窗
            flash(f'文章[ { title } ]已批量删除')
        return redirect(url_for('user.manage_del_mod'))
    return render_template('user/batchop.html',posts=posts, pagination=pagination)

Mynote/myNote/app/templates/user/batchop.html
{% extends 'base/base.html' %}

{% from 'base/macro.html' import pagination_show %}

{% block title %} justNote {% endblock %}

{% block page_content %}

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex justify-content-center" id="experience">
    <div class="w-100">
        <h3 class="mb-5">管理</h3>

        <hr class="m-6">


        <form action="{{ url_for('user.manage_del_mod') }}" method='POST'>

            {% for post in posts %}
                    <a class="btn  btn-primary"href="{{ url_for('user.editnote', id=post.id) }}">
                        编辑
                </a>
                    <a class="btn  btn-default" href="{{ url_for('main.post', id=post.id) }}">

                        详情

                </a>

                <input type="checkbox" name="array" value="{{ post.id }}">
                id：<font color="red"> {{ post.id }} </font>|
                title：<font color="red"> {{ post.title }} </font> |
                <a href="{{ url_for('user.delete', id=post.id) }}"
                   onclick="{if(confirm('确定纪录吗?')){this.document.formname.submit();return true;}return false;}"><span
                        class="label label-primary"><button class="btn  btn-danger"><i class="fa fa-pencil-square-o"
                                                       aria-hidden="true"></i>主公三思</button></span></a>
                </tb>
                <hr>
            {% endfor %}

            <input type='submit' onclick="return confirm('你确定要批量删除吗？');" value='批量删除'>
<div class="justify-content-center ">
          {{ pagination_show(pagination,'user.manage_del_mod') }}
          </div>
        </form>
</div>


</section>


{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

Mynote/myNote/app/templates/user/change_icon.html
{% extends 'base/base.html' %}

{% block title %}
    修改头像
{% endblock %}

{% block page_content %}
    修改头像
    {{ wtf.quick_form(form) }}
    <label>头像</label>
    <img src="{{ url_for('static',filename='uploads/photos/'+current_user.icon) }}"
    style="width:64px;height: 64px;">



{% endblock %}

Mynote/myNote/app/templates/user/change_password.html
{% extends 'base/base.html' %}

{% block title %}
    修改密码
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

Mynote/myNote/app/templates/user/editnote.html
{% extends "base/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}编辑文章{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row" style="padding:50px 20px;">
        <div class="col-md-12">
            <div class="page-header">
                <h3>编辑文章</h3>
            </div>
            <div>
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

Mynote/myNote/app/templates/user/getnote.html
{% extends 'base/base.html' %}

{#{% from 'common/macro.html' import pagination_show %}#}
{##}
{% block title %}编辑文章{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row" style="padding:50px 20px;">
        <div class="col-md-12">
            <div class="page-header">
                <h3>编辑文章</h3>
                <hr>
            </div>
            <div>
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

Mynote/myNote/app/templates/user/login.html
{% extends 'base/base.html' %}

{% block title %}
    用户登录
{% endblock %}

 

{% block page_content %}
    <hr>

    <div class="container center-block">
    <div class="row">
           <div class="col-md-4 "></div>
          <div class="col-md-auto">
          {{ wtf.quick_form(form) }}
              <p><a href="{{ url_for('user.register') }}">注册</a></p>
      </div>
        <div class="col-md-4">

        </div>
    </div>
    </div>









{% endblock %}

Mynote/myNote/app/templates/user/profile.html
{% extends 'base/base.html' %}

{% block title %}
    个人信息
{% endblock %}



{% block page_content %}


{#    <div class="five wide computer five wide tablet sixteen wide mobile column">#}
{#        <div class="form-group">#}
{#            <label>用户名</label>#}
{#            <input type=text class="form-control" id="InputUsername" placeholder="Username" disabled="disabled"#}
{#                   value={{ current_user.username }}>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <label>邮  箱</label>#}
{#            <input type=text class="form-control" id="InputEmail" placeholder="Email" disabled="disabled"#}
{#                   value={{ current_user.email }}>#}
{#        </div>#}
{##}
{#        <label>头  像</label>#}
{#        <br/>#}
{#        <img src="{{ url_for('static',filename='upload/'+current_user.icon) }}">#}
{#    </div>#}
{##}
{##}
{#    <div class="eleven wide computer eleven wide tablet sixteen wide mobile column">#}
{##}
{#            <div class="space-index-container">#}
{##}
{#            </div>#}
{#    </div>#}



    <div class="row">





<div class="container"><!--1170px-->

    <div>
    <div class="col-xs-2 col-md-5">
{#            <label>头 像</label>#}
            <br/>
            <img src="{{ url_for('static',filename='uploads/photos/'+current_user.icon) }}">
            <br/>

        </div>

            <div class="col-xs-8 col-md-6">
            <button class="btn btn-default" ><a href={{ url_for('user.change_password') }}>修改密码</a></button>
            <button class="btn btn-default" ><a >修改头像</a></button>
                <button class="btn btn-danger" ><a href={{ url_for('user.logout') }}>退出</a></button>

                 <div class="form-group">
                <label>用户名</label>
                <input type=text class="form-control" id="InputUsername" placeholder="Username" disabled="disabled"
                       value={{ current_user.username }}>
            </div>
            <div class="form-group">
                <label>邮 箱</label>
                <input type=text class="form-control" id="InputEmail" placeholder="Email" disabled="disabled"
                       value={{ current_user.email }}>
            </div>
                </div>

            </div>
    <div class="jumbotron">
        <h2>写文章</h2>
        <p>开源</p>
        <button class="btn btn-default"><a href={{ url_for('user.note') }}>说些什么</a></button>
        <button class="btn btn-default"><a href={{ url_for('user.manage_del_mod') }}>管理文章</a></button>
    </div>
</div>


    </div>
{% endblock %}

Mynote/myNote/app/templates/user/register.html
{% extends 'base/base.html' %}

{% block title %}
    用户注册
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}

{% endblock %}

Mynote/myNote/app/templates/user/unconfirmed.html
{% extends 'base/base.html' %}

{% block title %}
    未激活
{% endblock %}

 

{% block page_content %}
    <hr>

    <div class="container center-block">
        <div class="row">
            <div class="col-md-4 "></div>
            <div class="col-md-auto">
                未激活

                <div class="page-header">
                    <h>Hello, {{ current_user.username }}</h>
                    <div>
                        <h>You have not confirmed your account yet.</h>
                        Before you can access this site you need to
                        confirm your account.Check your inbox, you should have received an email with a confirmation
                        link
                        <p>Need another confirmathion link? <a href="{{ url_for('user.resend_confirmation') }}">Click
                            here</a></p>

                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}